version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - /data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    restart: on-failure
    volumes:
      - ./logs:/usr/src/logs/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
  test:
    build:
      context: ./
      dockerfile: ./test/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - web