version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    restart: on-failure
    volumes:
      - ./logs:/usr/src/logs/
    env_file:
      - .env
    ports:
      - "8000:8000"
  redis:
    image: redis
    restart: on-failure
#  test:
#    build:
#      context: ./
#      dockerfile: ./test/Dockerfile
#    env_file:
#      - .env
#    depends_on:
#      - web